name: Run Bruno Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bruno-test:
    name: Execute Bruno CLI Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code from the repo
        uses: actions/checkout@v3

      # Setting up Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' 
          
      # Install Bruno CLI
      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      # Run Bruno CLI tests with GraphQL_Project_Demo
      - name: Run Bruno Tests
        run: |
          cd GraphQL_Project_Demo
          bru run --reporter-html ../GraphQL_Project_Demo/Results.html

      # Upload the html test report as an artifact
      - name: Upload Test Report in artifact location
      # The below line will make this run, even if a previous step fails  
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Bruno HTML Test Result
          path: ./GraphQL_Project_Demo/Results.html
